"""Regenerates ../assets.js.

    pip install pillow numpy
    python3 tools/make_assets.py path/to/dinner-image.webp path/to/start-image.webp
"""
import base64, io, json, mimetypes, os, sys
sys.path.insert(0, os.path.dirname(__file__))
from PIL import Image
from table_scene import table_scene

def uri(rgb):
    b = io.BytesIO(); Image.fromarray(rgb).save(b, 'PNG', optimize=True)
    return 'data:image/png;base64,' + base64.b64encode(b.getvalue()).decode()

def file_uri(path):
    mime = mimetypes.guess_type(path)[0] or 'image/png'
    return f'data:{mime};base64,' + base64.b64encode(open(path, 'rb').read()).decode()

rgb = table_scene(sys.argv[1])
assets = dict(table=dict(bg=uri(rgb), w=rgb.shape[1], h=rgb.shape[0]), start=dict(bg=file_uri(sys.argv[2])))
out = os.path.join(os.path.dirname(__file__), '..', 'assets.js')
with open(out, 'w') as f:
    f.write('// Generated by tools/make_assets.py - images for the game.\nwindow.ASSETS = ' + json.dumps(assets) + ';\n')
print('wrote', out)
